services:
  server:
    build:
      context: src
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./certs:/certs
    ports:
      - 80:80 # http
      - 443:443/tcp # https
      - 443:443/udp # http/3
