[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "openocc"
dynamic = ["version"]
dependencies = [
  "aioquic",
  "aiortc",
  "requests",
]
authors = [
  {name = "Björn Otto", email = "bjoern.otto@ovgu.de"},
]
readme = "README.md"

[tool.setuptools.dynamic]
version = {attr = "openocc.__version__"}


