CREATE TABLE IF NOT EXISTS vehicles (
    id   TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    lat  DOUBLE PRECISION NOT NULL DEFAULT 0,
    lon  DOUBLE PRECISION NOT NULL DEFAULT 0,
    key  TEXT NOT NULL DEFAULT ''
);
